ezsystems/ezplatform-xmltext-fieldtype

- lib/FieldType/XmlText/Converter/Expanding.php
- tests/lib/FieldType/Converter/_fixtures/expanding/input/008-table.xml
- tests/lib/FieldType/Converter/_fixtures/expanding/input/010-simpleParagraphs.xml
- tests/lib/FieldType/Converter/_fixtures/expanding/input/011-lists.xml
- tests/lib/FieldType/Converter/_fixtures/expanding/output/008-table.xml
- tests/lib/FieldType/Converter/_fixtures/expanding/output/010-simpleParagraphs.xml
- tests/lib/FieldType/Converter/_fixtures/expanding/output/011-lists.xml
- tests/lib/FieldType/Converter/_fixtures/html5/input/009-itemizedList.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/009-itemizedList.xml
JIRA: https://jira.ez.no/browse/EZP-24710
When a XmlText field is  edited in the legacy admin interface with Online Editor disabled, the paragraphs are not rendered. This is happening because in this setup, the legacy eZSimplifiedInputParser generates the paragraph with the `xml:tmp` namespace definition and since the fix of [EZP-23513](https://jira.ez.no/browse/EZP-23513) (in https://github.com/ezsystems/ezpublish-kernel/pull/1087), those paragraphs are set as temporary and then ignored in the XSLT stylesheet.
This patch improves the temporary paragraph check to not use only the `xml:tmp` attribute as it seems the legacy input parsers are not strict enough on it.
unit tests + manual tests
> EZP-24710: Paragraphs are stripped on the front-end if an XML block is published with the editor disabled

- lib/FieldType/XmlText/Input/Resources/schemas/ezxml.xsd
- tests/lib/FieldType/Converter/_fixtures/html5/input/027-multilineheading.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/027-multilineheading.xml
- tests/lib/FieldType/Input/EzXmlTest.php
JIRA: https://jira.ez.no/browse/EZP-25116
In the ezxml schema of XmlText, the `header` element does not accept `line` as a child while in legacy this is available since https://github.com/ezsystems/ezpublish-legacy/pull/930 ([EZP-22563](https://jira.ez.no/browse/EZP-22563)). As a result, it is impossible to represent a line break in a header.
This patch updates the ezxml schema (and the unit tests) to be consistent with the feature provided by the legacy Online Editor. This way the following ezxml document can be set on an XmlText fields:
```xml
<?xml version="1.0" encoding="utf-8"?>
<section>
<header>
<line>Header</line>
<line><custom name="underline">underline</custom></line>
<line>level</line>
<line>1</line>
</header>
</section>
```
and will be rendered as:
```html …
```
> EZP-25116: Impossible to add line break in header element

- tests/lib/XmlTextAPIIntegrationTest.php
Use `RelationSearchBaseIntegrationTestTrait` instead of deprecated `RelationSearchBaseIntegrationTest`.
> Changed usage of deprecated test class

- README.md
- bundle/Command/ConvertXmlTextToRichTextCommand.php
- bundle/Resources/config/services.yml
> Status: partially tested prototype
Converted from procedural script provided by @pspanja, related doc being added to kernel: https://github.com/ezsystems/ezpublish-kernel/pull/1560
Will, at database level:
- replace `ezxmltext` field definitions with `ezrichtext` ones
- convert the content of `ezxmltext` fields to richtext
Regular output will display number of converted field definitions and values. Actual converted values will be logged, and can be displayed by adding the `-v` command option.
Tried on the `ezdemo` data set from eZ Publish Platform 5.4.0.
> EZP-25358: ezxmltext:convert-to-richtext command prototype

- lib/FieldType/XmlText/Type.php
- tests/lib/FieldType/XmlTextTest.php
JIRA: https://jira.ez.no/browse/EZP-25743
https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/12 against 1.1
> Fix EZP-25743: empty tagPreset error in fieldType validation

- lib/FieldType/XmlText/Converter/EmbedLinking.php
- lib/FieldType/XmlText/Converter/EmbedToHtml5.php
- tests/lib/FieldType/Converter/EmbedToHtml5Test.php
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/001-embedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/004-inlineEmbedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/006-inlineEmbedContentLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/007-inlineEmbedUrlLinkMixed.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/001-embedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/004-inlineEmbedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/006-inlineEmbedContentLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/007-inlineEmbedUrlLinkMixed.xml
JIRA: https://jira.ez.no/browse/EZP-26962
Same as https://github.com/ezsystems/ezpublish-kernel-ee/pull/152, just waiting for Travis to pass
> Fix EZP-26962: Error generated in log when viewing an XmlText field containing an embed with an external link

- bundle/Resources/config/templating.yml
> https://jira.ez.no/browse/EZP-27308
Service names will become case sensitive in later Symfony versions.
> EZP-27308: Remove deprecated usage of Symfony services

- .travis.yml
- composer.json
- tests/lib/FieldType/Converter/EmbedToHtml5Test.php
Sudo method needs to be mocked to run the tests on newer versions of eZ kernel, due to introduction of permissions resolver.
Also adds some more variations of tests to matrix on Travis.
Finally, we limit Solr bundle to 1.2 because master installs config for Solr 6
> Improvements in tests setup

- lib/FieldType/XmlText/Converter/EmbedToHtml5.php
- tests/lib/FieldType/Converter/EmbedToHtml5Test.php
This is a fix for https://jira.ez.no/browse/EZP-27396
Embeding inline objects in case it's only element in paragraph produces following xml which is then saved into DB:
```
<paragraph><embed-inline view="embed-inline" size="medium" object_id="126">ezembed</embed-inline></paragraph>
```
The **ezembed** part was not removed by `EmbedToHtml5` which resulted in invalid object embeding on further processing.
Fixing this is just clearing text content of XmlNode in case of `<embed>` and `<embed-inline>` elements
> EZP-27396 Fixing inline object embeding

- .travis.yml
- composer.json
- lib/FieldType/XmlText/XmlTextStorage.php
- lib/FieldType/XmlText/XmlTextStorage/Gateway.php
- lib/FieldType/XmlText/XmlTextStorage/Gateway/LegacyStorage.php
- lib/settings/fieldtype_external_storages.yml
- lib/settings/storage_engines/legacy/external_storage_gateways.yml
- tests/lib/XmlTextSPIIntegrationTest.php
This PR adds the new storage gateway API for field types introduced in https://github.com/ezsystems/ezpublish-kernel/pull/1985
Since this field type in its storage gateway uses `ezurl` storage gateway from eZ kernel, there's no sane way to keep backwards compatibility with previous versions of eZ kernel and the only way to fix the field type is to switch to the new API completely.
For that reason, this also bumps master to 1.3.
> Use new storage gateway API for 6.11 compatibility

- lib/FieldType/XmlText/Converter/EmbedToHtml5.php
- tests/lib/FieldType/Converter/EmbedToHtml5Test.php
Makes sure we use the new view API from https://github.com/ezsystems/ezpublish-kernel/pull/1454.
Don't know if this is something we should do? Is this bundle be supposed to migrated to 5.4? In that case this is invalid then.
> Use the new view API from eZ Publish kernel

- composer.json
- tests/bundle/DependencyInjection/Compiler/XmlTextConverterPassTest.php
- tests/lib/FieldType/Converter/EmbedLinkingTest.php
- tests/lib/FieldType/Converter/EmbedToHtml5Test.php
- tests/lib/FieldType/Converter/ExpandingTest.php
- tests/lib/FieldType/Converter/EzLinkToHtml5Test.php
- tests/lib/FieldType/Converter/Html5Test.php
- tests/lib/FieldType/Gateway/LegacyStorageTest.php
- tests/lib/FieldType/Input/EzXmlTest.php
- tests/lib/FieldType/XmlTextTest.php
- tests/lib/Persistence/Legacy/Content/FieldValue/Converter/XmlTextTest.php
- tests/lib/REST/Common/FieldTypeProcessor/XmlTextProcessorTest.php
- tests/lib/XmlTextAPIIntegrationTest.php
This PR resolves:
* PHPUnit updated to 5.7
* tests now extend namespaced `TestCase`
* removed deprecated `getMock()` method
* removed unused `zendframework\zend-code` dependency
* class constants used wherever possible
* tests autoloaded with `autoload-dev`
* `composer.json` now uses 4 space indent like on other repos
> Updated PHPUnit to 5.7

- bundle/Resources/config/fieldtype_services.yml
- lib/FieldType/XmlText/InternalLinkValidator.php
- lib/FieldType/XmlText/Type.php
- lib/settings/fieldtypes.yml
- tests/lib/FieldType/InternalLinkValidatorTest.php
> JIRA:  https://jira.ez.no/browse/EZP-28174
This PR adds validation of `ezobject://` and `eznode://` links in the xml text field type. 
_This is follow up for ezsystems/ezpublish-legacy#1333 and ezsystems/ezpublish-kernel#2154_
> EZP-28174: Validation of ezobject:// and eznode:// links in the xml text field type

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_core.xsl
- tests/lib/FieldType/Converter/_fixtures/html5/output/014-link.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/104-expandAndLinkEmbed.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/105-expandAndLinkEmbedWrapped.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/106-expandAndLinkEmbedDoubleWrapped.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/107-expandAndLinkEmbedDoubleWrapped2.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/109-expandEmbedInline.xml
JIRA issue: https://jira.ez.no/browse/EZP-28623
URL to the unaccessible linked content shouldn't be rendered as an anchor with empty `href` attribute. The whole anchor should be omitted, and only the wrapping paragraph should be rendered during the XML to HTML5 conversion.
> EZP-28623: Display paragraph when user haven't permissions to see linked content

- lib/FieldType/XmlText/Converter/ExpandingToRichText.php
The test [`EzxmlToDocbookTest::testConvert#23`](https://github.com/ezsystems/ezpublish-kernel/commit/3a6a6ec078fc23faab95aebb50da1eff97861919#diff-429a392f5d946a60380b9ac60dae0693R8) in kernel is failing : 
```diff
1) eZ\Publish\Core\FieldType\Tests\RichText\Converter\Xslt\EzxmlToDocbookTest::testConvert with data set #23 ('/var/www/external/ezpublish-k...te.xml', '/var/www/external/ezpublish-k...te.xml')
Failed asserting that two DOM documents are equal.
Input file: /var/www/external/ezpublish-kernel/eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/ezxml/024-template.xml
Output file /var/www/external/ezpublish-kernel/eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/024-template.xml
Failed asserting that two DOM documents are equal.
--- Expected …
```
> Removed extra <para> when converting custom tag from ezxmltext to richtext

- lib/FieldType/XmlText/Converter/EmbedLinking.php
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/001-embedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/004-inlineEmbedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/006-inlineEmbedContentLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/input/007-inlineEmbedUrlLinkMixed.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/001-embedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/004-inlineEmbedUrlLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/006-inlineEmbedContentLink.xml
- tests/lib/FieldType/Converter/_fixtures/embed_linking/output/007-inlineEmbedUrlLinkMixed.xml
This fixes a regression caused by [EZP-26962](https://jira.ez.no/browse/EZP-26962) and https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/17
After the fix of EZP-26962, the attribute `ezlegacytmp-embed-link-url_id` is no more used by the ezxmltext -> xhtml conversion, but it is still used by ezxmltext -> richtext
> EZP-29258 Convertion of Embeds with links from ezxmltext to richtext is broken

- lib/FieldType/XmlText/Converter/RichText.php
- tests/lib/FieldType/Converter/_fixtures/richtext/input/121-embed-no_idref.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/132-embed-inline-no_idref.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/121-embed-no_idref.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/132-embed-inline-no_idref.xml
Outputs warning if ezxmltext contains `<embed>` or `<embed-inline>` tags which do not have `node_id=...` or `object_id=...` attributes
~Depends on [this kernel fix](https://github.com/ezsystems/ezpublish-kernel/pull/2320)~. No longer correct due to https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/46
Note : One test is failing.. That test is fixed in an separate PR (which for now have been merged to wrong branch)
> Fixed EZP-29135 : Converting ezxmltext to richtext when embed tag contains neither node_id or object_id fails

- lib/FieldType/XmlText/Converter/ExpandingToRichText.php
- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/041-link_href.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/041-link_href.xml
Handling of tags in format <link href="http://foobar.com" ...> is missing in xsl stylesheet
> EZP-29267: Convertion of links with href from ezxmltext to richtext is not supported

- bundle/Command/ConvertXmlTextToRichTextCommand.php
- lib/FieldType/XmlText/Converter/RichText.php
- tests/lib/FieldType/Converter/RichTextTest.php
- tests/lib/FieldType/Converter/_fixtures/richtext/input/041-anchor_invalid_id.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/log/001-dupid-title.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/002-dupid-embed.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/003-dupid-anchor.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/041-anchor_invalid_id.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/121-embed-no_idref.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/132-embed-inline-no_idref.log
- tests/lib/FieldType/Converter/_fixtures/richtext/output/041-anchor_invalid_id.xml
This PR fixes [EZP-29289](https://jira.ez.no/browse/EZP-29289)
It is not 100% bulletproof though;
- ~It checks if first character in the attribute's value is white listed. It does not check the remaining characters. It would be possible to fix that, but it would require yet another XPath pass I believe.~
-  Also, the whitelist may not be 100% complete
But I think this is good enought for now
> EZP-29289: Migrating ezxmltext with invalid name or id attributes

- bundle/Command/ConvertXmlTextToRichTextCommand.php
- bundle/Command/ConvertXmlTextToRichTextCommandSubProcess.php
- bundle/Resources/config/services.yml
- lib/FieldType/XmlText/Converter/RichText.php
This PR adds `--concurrency=...` option to ezxmltext conversion command. This will speed up conversion on multi core hardware.
Also, the conversion script no longer loads the whole `ezcontentobject_attribute` table into memory at launch....
> Added multiconcurrency support in ezxmltext convert command

- bundle/Command/ConvertXmlTextToRichTextCommand.php
Bugs found:
- last 1000 records where skipped when converting
- script waited for all but one  worker to finish
- option --fix-embedded-images-only got broken
> Fix regressions caused by multiconcurrency pr #49

- lib/FieldType/XmlText/Converter/RichText.php
- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/RichTextTest.php
- tests/lib/FieldType/Converter/_fixtures/richtext/input/042-link_object_remote_id.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/043-link_object_remote_id_invalid.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/044-link_unhandled_link_type.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/045-link_node_remote_id.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/046-link_node_remote_id_invalid.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/log/043-link_object_remote_id_invalid.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/044-link_unhandled_link_type.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/046-link_node_remote_id_invalid.log
- tests/lib/FieldType/Converter/_fixtures/richtext/output/042-link_object_remote_id.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/043-link_object_remote_id_invalid.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/044-link_unhandled_link_type.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/045-link_node_remote_id.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/046-link_node_remote_id_invalid.xml
Fixes [EZP-29339](https://jira.ez.no/browse/EZP-29339)
Adds support for links like
```
<?xml version="1.0" encoding="utf-8"?>
<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/">
<paragraph>foobartext
<link object_remote_id="my_remote_id">link</link>
</paragraph>
</section>
```
> Fix  EZP-29339: ezxmltext -> ricktext conversion : links with object_remote_id="..." not suppor

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/010-align.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/010-align.xml
Fixes [EZP-29349](https://jira.ez.no/browse/EZP-29349)
Values like -webkit-auto, and others needs to be handled as RichText is more strict and only supports left, right, center & justify.
> EZP-29349: ezxmltext -> ricktext conversion : exotic align values fail

- bundle/Command/ConvertXmlTextToRichTextCommandSubProcess.php
"setHidden" from Command class is undefined in Symfony 2.8 (it appeared in Symfony 3.2). This causes errors when clearing cache with EzSystemsEzPlatformXmlTextFieldTypeBundle enabled on eZ Platform 1.13.
> Fix "setHidden" method being undefined in Symfony 2.8

- lib/FieldType/XmlText/Converter/RichText.php
- tests/lib/FieldType/Converter/_fixtures/richtext/input/081-header-with-embed.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/091-table-empty-row.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/146-paragraph-temporary-ez-temporary.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/150-literal.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/log/081-header-with-embed.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/146-paragraph-temporary-ez-temporary.log
- tests/lib/FieldType/Converter/_fixtures/richtext/output/081-header-with-embed.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/146-paragraph-temporary-ez-temporary.xml
This one fixes [ezp-29480](https://jira.ez.no/browse/EZP-29480)
It also adds a test case for https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/56
> EZP-29480: ezxmltext -> richtext conversion : ezxmltext containing ez-temporary attribute

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/092-table-width.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/092-table-width.xml
This one fixes [EZP-29507](https://jira.ez.no/browse/EZP-29507)
> EZP-29507: ezxmltext -> richtext conversion: width attribute in table|tr|th elements containing "px"

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/011-align-embed.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/011-align-embed.xml
This one fixes [EZP-29529](https://jira.ez.no/browse/EZP-29529)
> EZP-29529: ezxmltext -> richtext conversion: <ezembed> do not support align='justify'

- lib/FieldType/XmlText/Converter/ExpandingToRichText.php
- tests/lib/FieldType/Converter/_fixtures/richtext/input/149-paragraph-with-header.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/149-paragraph-with-header.xml
This one fixes [EZP-29595](https://jira.ez.no/browse/EZP-29595)
The implementation of this one is different compared to https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/72 because we already have generic functionality for dealing with this kind of stuff  on paragraphs.
The downside is that no warnings or notices are logged on such occurrences though
> EZP-29595: ezxmltext -> richtext conversion : <header> inside <paragraph>

- tests/lib/FieldType/Converter/MethodCallCountConstraint.php
- tests/lib/FieldType/Converter/RichTextTest.php
- tests/lib/FieldType/Converter/_fixtures/richtext/log/002-dupid-embed.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/003-dupid-anchor.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/081-header-with-embed.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/150-literal.log
Testsystem would not yell if conversion would fail with unexpected schema validation error.
Ref. https://github.com/sebastianbergmann/phpunit-mock-objects/issues/65
> Fixed RichTextTest so that tests fails if unexpected logs messages are created

- lib/FieldType/XmlText/Converter/RichText.php
- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/160-eztemplate.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/170-eztemplateinline.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/log/160-eztemplate.log
- tests/lib/FieldType/Converter/_fixtures/richtext/log/170-eztemplateinline.log
- tests/lib/FieldType/Converter/_fixtures/richtext/output/160-eztemplate.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/170-eztemplateinline.xml
This one fixes [EZP-29634](https://jira.ez.no/browse/EZP-29634)
> EZP-29634: ezxmltext -> richtext conversion : <custom> inside <section>

- bundle/Command/ConvertXmlTextToRichTextCommand.php
- bundle/Command/ImportXmlCommand.php
In response to https://github.com/ezsystems/ezplatform-xmltext-fieldtype/issues/77
> PostgreSQL do not support alias in update queries

- bundle/Command/ConvertXmlTextToRichTextCommand.php
- bundle/Resources/config/services.yml
- lib/FieldType/XmlText/Converter/RichText.php
This one implements [EZP-29697](https://jira.ez.no/browse/EZP-29697)
This PR adds a report of custom tags being processed during conversion
Example:
```
Custom tags overview
====================
Below are the list of custom tags found during conversion of ezxmltext fields
Inline custom tags
------------------
* custom3
* custom4
Block custom tags
-----------------
* factbox
* custom1
* custom2
```
> EZP-29697: ezxmltext -> richtext conversion : Give user a report of custom tag usage

- composer.json
- lib/FieldType/XmlText/Converter/RichText.php
- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/150-literal.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/151-literal-class-html.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/log/150-literal.log
- tests/lib/FieldType/Converter/_fixtures/richtext/output/150-literal.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/151-literal-class-html.xml
This PR implements [EZP-29027](https://jira.ez.no/browse/EZP-29027)
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2430
(tests fails due to that)
> EZP-29027: Added support for conversion of ezxmltest tag <literal> 

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_core.xsl
- tests/lib/FieldType/Converter/_fixtures/html5/input/111-linkembed.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/111-linkembed.xml
Based on https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/83, added test
> xhtml output : support for linkable embeds

- bundle/Command/ConvertXmlTextToRichTextCommand.php
- bundle/Command/ImportXmlCommand.php
This PR adds:
- Progress bar to `ezxmltext:convert-to-richtext` script
- Outputs non-validating docbook xml (indented) when running `ezxmltext:import-xml` script using `--content-object`
The `ezxmltext:convert-to-richtext` script may run for quite some time on large databases and the lack of progress bar could give the user an impression that it didn't do anything
The output of docbook xml helps user to figure out what is wrong when fixing bad ezxmltext markup
> UI improvements

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_core.xsl
- tests/lib/FieldType/Converter/_fixtures/html5/input/112-removeCustomTagsWrappingParagraph.xml
- tests/lib/FieldType/Converter/_fixtures/html5/output/112-removeCustomTagsWrappingParagraph.xml
JIRA issue: [EZP-29331](https://jira.ez.no/browse/EZP-29331)
When rendering XML block Field inside new stack consecutive Custom Tags will be rendered inside unwanted additional `<p>` tag. This PR fixes this issue by searching for a paragraph with no text and only `<custom>` tags inside and deletes it, putting its children in its place.
**Todo:**
> EZP-29331: Custom Tags added in Legacy Bridge gets rendered inside paragraph in the new stack

- bundle/Resources/config/services.yml
- lib/FieldType/XmlText/Converter/RichText.php
- tests/lib/FieldType/Converter/EzxmlToDocbookTest.php
- tests/lib/FieldType/Converter/RichTextTest.php
// maintainer update:
Injecting proper DIC service will result in implicit swapping of this Validator when RichText bundle is enabled (it replaced `eZ\Publish\Core\FieldType\RichText`).
_Note: if we intend to somehow support this bundle still with 3.0, then we will have to bump requirements and inject proper service from the RichText bundle_
> Injected RichText Validator from DIC into RichText Converter

- composer.json
- phpunit.xml
- tests/lib/FieldType/Converter/MethodCallCountConstraint.php
This reverts commit 26b421780a8add0544b884062b4aa8bcaf089a86.
For testing Travis failure on mysql/postgres tests.
> Revert "[Tests] Move to phpunit 7 & add paratest"

- lib/Persistence/Legacy/Content/FieldValue/Converter/XmlTextConverter.php
- lib/settings/fieldtypes.yml
- lib/settings/indexable_fieldtypes.yml
- lib/settings/storage_engines/legacy/field_value_converters.yml
| **JIRA issue**     | N/A
| **Type**           | Improvement
| **Target version** | `master`
| **BC breaks**      | yes
**TODO**:
> Replace deprecated field type tags

- bundle/DependencyInjection/Configuration/Parser/FieldType/XmlText.php
- bundle/Resources/config/default_settings.yml
- bundle/Resources/config/fieldtype_services.yml
- bundle/Resources/config/services.yml
- bundle/Resources/config/templating.yml
- lib/settings/fieldtype_external_storages.yml
- lib/settings/fieldtypes.yml
- lib/settings/indexable_fieldtypes.yml
- lib/settings/storage_engines/legacy/external_storage_gateways.yml
- lib/settings/storage_engines/legacy/field_value_converters.yml
- tests/bundle/DependencyInjection/Configuration/Parser/FieldType/XmlTextTest.php
| **JIRA issue**     | N/A
| **Type**           | Improvement
| **Target version** | `master`
| **BC breaks**      | yes
**TODO**:
> Remove class parameters

- .travis.yml
| **JIRA issue**     | n/a
| **Type**           | Misc
| **Target version** | 1.7 - same as https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/96
All PHP 5.6 jobs are failing on Travis because of memory issues, see: https://travis-ci.org/ezsystems/ezplatform-xmltext-fieldtype/builds/566005333?utm_source=github_status&utm_medium=notification
I suppose we could try limiting the minimum supported versions in requirements in this bundle:
```
"require": {
"ezsystems/ezpublish-kernel": "^6.11@dev || ^7.0@dev",
"ezsystems/repository-forms": "^1.9 || ^2.0"
},
```
but as I don't know with which version is the 1.7 line intended to be used. To avoid preventing users …
> [Travis] Add swap to avoid hitting memory issues

- .travis.yml
| **JIRA issue**     | n/a
| **Type**           | Misc
| **Target version** | 1.7, same as https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/98
Travis switched the default dist from trusty to xenial:
https://travis-ci.org/ezsystems/ezplatform-xmltext-fieldtype/builds/567807165 - uses trusty
https://travis-ci.org/ezsystems/ezplatform-xmltext-fieldtype/builds/569339518 - uses xenial
This is causing the builds in https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/98 to fail.
Setting the dist excplicitly as it is done in 1.8 branch: https://github.com/ezsystems/ezplatform-xmltext-fieldtype/blob/1.8/.travis.yml#L1
> [Travis] Set dist to trusty

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/002-para.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/022-embed.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/024-template.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/002-para.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/022-embed.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/024-template.xml
| **JIRA issue**     | [EZP-30507](https://jira.ez.no/browse/EZP-30507)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `1.7`
| **Tests pass**     | yes
There is a strict list of possible values for ezxhtml:textalign: https://github.com/ezsystems/ezplatform-richtext/blob/master/src/lib/eZ/RichText/Resources/schemas/docbook/ezpublish.rng#L744-L756.
So custom values there were causing validation errors. This PR fixes it.
**TODO**:
> EZP-30507: Strict possible values for align attribute

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/024-template.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/161-eztemplate-no-content.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/log/161-eztemplate-no-content.log
- tests/lib/FieldType/Converter/_fixtures/richtext/output/161-eztemplate-no-content.xml
| **JIRA issue**     |     [EZP-31130 : {{ content }} variable not always available in twig template for custom tag](https://jira.ez.no/browse/EZP-31130)
| **Type**           | Improvement
| **Target version** | 1.8
This change is to ensure conversion script creates customtags in the same way as admin-ui ( even though the previous behaviour also was also valid schema wise). admin-ui always creates a `<ezcontent/>` element below `eztemplate`, even though the custom tags has no content..
eZ Platform version 2.5.6 and earlier will give fatal error on the following twig code for `<eztemplate>`  elements which has no `<ezcontent/>` sub element:
```
{{ content|raw }}
``` …
> Ensure <eztemplate> elements contains <ezcontent> child

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/027-linkedEmbed.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/027-linkedEmbed.xml
| **JIRA issue**     | [EZP-31474](https://jira.ez.no/browse/EZP-31474)
| **Type**           | Bug
| **Target version** | 1.9
Currently, the converter works incorrectly for this XML:
```
<?xml version="1.0" encoding="utf-8"?>
<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/">
<paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/">
<link anchor_name="maincontent">
<embed size="original" align="top" node_id="241190"/>
</link>
</paragraph>
</section>
```
It will result to empty <link/> object inserted into embed
```
<ezembed …
```
> EZP-31474 - fix embed anchor link converting to richtext

- .php_cs
- README.md
- bundle/Command/ConvertXmlTextToRichTextCommand.php
- bundle/Command/ImportXmlCommand.php
- lib/FieldType/XmlText/Converter/RichText.php
- lib/FieldType/XmlText/Persistence/Legacy/ContentModelGateway.php
- lib/FieldType/XmlText/SearchField.php
- lib/FieldType/XmlText/XmlTextStorage/Gateway/DoctrineStorage.php
- tests/lib/FieldType/Persistence/Legacy/BaseTest.php
- tests/lib/FieldType/Persistence/Legacy/ContentModelGatewayTest.php
- tests/lib/SetupFactory/LegacyEmptyDBSetupFactory.php
This PR fixes outstanding issues discovered by CI and upgrades code and test setup to be compatible with eZ Platform v3.0.
**I recommend fast-forward merge** because the PR contains out of scope fix for [EZP-31512](https://jira.ez.no/browse/EZP-31512) (see ezsystems/ezplatform-richtext#128 for details).
I've upgraded test setup not to rely on dropped eZc Database Handler and while at it updated code to rely on Doctrine instead of PDO (`PDO::FETCH_*` usages). Using PDO constants in relevant changed places is deprecated in Doctrine.
There was also one outstanding change - Symfony `ContextErrorException` has been dropped in Symfony 4.0 in favor of native `\ErrorException`.
**TODO**:
> Upgraded package to be compatible with eZ Platform v3.0

- lib/FieldType/XmlText/Converter/RichText.php
- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/027-linkedEmbed.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/docbook/028-linkedEmbedInline.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/lossy/104-expandAndLinkEmbed.docbook.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/lossy/105-expandAndLinkEmbedWrapped.docbook.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/lossy/106-expandAndLinkEmbedDoubleWrapped.docbook.xml
- tests/lib/FieldType/Converter/Xslt/_fixtures/ezxml/lossy/107-expandAndLinkEmbedDoubleWrapped2.docbook.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/input/122-embed-linked-image-add-is-linked.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/122-embed-linked-image-add-is-linked.xml
| **JIRA issue**     | https://issues.ibexa.co/browse/EZP-32345
| **Type**           | Bug
| **Target version** | `1.8`
This PR fixes the issue with the conversion command which caused links vanishing from the RichText editor by adding the missing `is-linked` class to the `<ezembed>` and placing `<ezlink>` tag after `<ezconfig>`.
**TODO**:
> Fixed missing 'is-linked' tag and wrong ezlink tag order

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/084-line-with-embed.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/084-line-with-embed.xml
| **JIRA issue**     | https://issues.ibexa.co/browse/EZEE-3495
| **Type**           | Bug
| **Target version** |  `1.8`
This PR adds missing handling for the `<line>` tag.
> Added missing templates for line tag

- lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Docbook_core.xsl
- tests/lib/FieldType/Converter/_fixtures/richtext/input/093-table-valign-center.xml
- tests/lib/FieldType/Converter/_fixtures/richtext/output/093-table-valign-center.xml
| **JIRA issue**     | https://issues.ibexa.co/browse/EZP-32359
In the legacy XML Text field, there was a possibility that the table cell will have `valign` attribute set to `center` (probably pasting from MS Word) which is not a valid docbook and will fail RichText validation after conversion. 
This PR adds a conversion rule, so `center` is cast to `middle` for `valign` attribute.
**TODO**:
> Added conversion rule for valign=center
